version: '3.4'

services:
  storedb:
    container_name: storedb
    restart: always
    ports:
      - "27017:27017"

  store.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - storedb
    ports:
      - "8000:80"
