version: '3.4'

services:
  storedb:
    image: mongo

  basketdb:
    image: redis:alpine

  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: Services/Store/Store.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

